### ISSUE TITLE
Let user select default currency

### ISSUE THREAD

**Issue by FelipePSoares** [FelipePSoares/EconoFlow#190]

**Comment by Dan-613** [comment]
@FelipePSoares Where would you store this within the data classes/database? In User.cs?

**Comment by FelipePSoares** [comment]
Yes, in User.cs would be a good place. If you want to do that I can write this issue properly.

**Comment by FelipePSoares** [comment]
I slipted this issue in more issues to solve the problem:

#240 
#241 
#242 
#243 
#244 
#245
