### ISSUE TITLE
[Backend] start to use Result Pattern to avoid exceptions

### ISSUE THREAD

**Issue by FelipePSoares** [FelipePSoares/EconoFlow#204]
Today we throw a exception when some validation get wrong, but it's not a good thing. 

To avoid throw exceptions all the time, we need to start to use result pattern. 

We need to create a base result model and then modify the validations to add a error message when some validation get wrong and return it to front end.

**Comment by AmirAbdollahi** [comment]
Hi @FelipePSoares,
I think this issue is interesting. May I start working on it?

**Comment by FelipePSoares** [comment]
Hi @AmirAbdollahi ,

For sure, it's a good moment to do that because now I'm a little bit busy and no one is working in the code, then no conflicts. Kkk

Behappy with that. Thank you for your help, feel free to ask anything.

**Comment by FelipePSoares** [comment]
Hi @AmirAbdollahi ,

For sure, it's a good moment to do that because now I'm a little bit busy and no one is working in the code, then no conflicts. Kkk

Behappy with that. Thank you for your help, feel free to ask anything.

If you want so example, I made it in another project.
https://github.com/FelipePSoares/MovieCollection/blob/main/MovieCollection.Infrastructure/DTOs/AppResponse.cs

**Comment by AmirAbdollahi** [comment]
Thank you @FelipePSoares,
It's incredibly helpful!. I'll review the `AppResponse` implementation in your `MovieCollection` repository to better understand your approach.

Thanks again for your support and guidance!
