### ISSUE TITLE
[Frontend] Change edit forms to use angular material

### ISSUE THREAD

**Issue by FelipePSoares** [FelipePSoares/EconoFlow#217]

**Comment by ahmedhalac** [comment]
Hi @FelipePSoares. Can I work on this?

**Comment by Dan-613** [comment]
I'm confused. Which edit forms are not using Angular Material?

**Comment by FelipePSoares** [comment]
Hi, @ahmedhalac Yes, you can do that. 

If you are in doubt which forms I'm talking about as @Dan-613. It's this forms when you select edit on list pages.

![image](https://github.com/user-attachments/assets/527decc7-5476-47f8-9bec-e84921c346cd)

**Comment by Dan-613** [comment]
> Hi @FelipePSoares. Can I work on this?

@ahmedhalac Just checking whether you'd like to handle this one?

**Comment by ahmedhalac** [comment]
Hi @Dan-613. I will handle this one.

**Comment by ahmedhalac** [comment]
Hi @Dan-613. I am having issues with the running the project. Is there any documentation with the instruction how to run project/install required dependecies?

**Comment by Dan-613** [comment]
I didn't have any issues with running it.
What IDE are you running it in? Visual Studio?

**Comment by ahmedhalac** [comment]
@Dan-613. No I am using VS code. 
<img width="1824" alt="Screenshot 2024-11-08 at 11 52 16 PM" src="https://github.com/user-attachments/assets/c843a422-9b2a-47af-aa20-c11fb94bf44e">

**Comment by Dan-613** [comment]
Let me get the latest version and test it. Give me a few minutes.

**Comment by Dan-613** [comment]
It's working fine for me.
Please can you put a breakpoint on this line and tell me what the values are for both sides of the ">" 
https://github.com/FelipePSoares/EconoFlow/blob/d8f1a576b237725c64026912ff6bbd9b805435db/EasyFinance.Domain/Financial/BaseFinancial.cs#L43

**Comment by ahmedhalac** [comment]
For some reason, it passed, but now I am getting another error:

<img width="1622" alt="Screenshot 2024-11-09 at 12 08 13 AM" src="https://github.com/user-attachments/assets/0a7e3f68-c17f-48c5-bda7-fc7596724f47">

Login method is returning 504, Gateway Timeout. 
I ran the app using the command: **dotnet run --configuration Debug**

**Comment by Dan-613** [comment]
Hmm. I'm not sure. Could you try running the project in Visual Studio? It may be something to do with how it was originally set up in Visual Studio. But that's a guess.

**Comment by FelipePSoares** [comment]
Sorry guys, I was off this weekend, @Dan-613 thank you for your help.

I'll write a instructions how to run the project , to help future collaborators, but to run the project in VS Code it's just use the line below:

`dotnet run --project ./EasyFinance.Server --urls https://localhost:7003/`
