### ISSUE TITLE
[Frontend] Make layout of forms more mobile friendly

### ISSUE THREAD

**Issue by Dan-613** [FelipePSoares/EconoFlow#219]
Layout on a mobile display gets too tight for mobile users. Move the input boxes below each other so each input box has the full width on mobile layouts.
![image](https://github.com/user-attachments/assets/bf97e0f1-cd26-4edf-9217-40b5676adca6)

**Comment by FelipePSoares** [comment]
Hi @Dan-613 ,

I'll close it because this need to be done when we chance the form to use angular material.

https://github.com/FelipePSoares/EconoFlow/issues/217#issuecomment-2460955775
