### ISSUE TITLE
[Frontend] Apply angular material in edit forms

### ISSUE THREAD

**Issue by FelipePSoares** [FelipePSoares/EconoFlow#239]
To keep the pattern in the application we need to apply angular material in all forms, currently we are not using in some edit forms. you can use [list-expenses](https://github.com/FelipePSoares/EconoFlow/blob/master/easyfinance.client/src/app/features/expense/list-expenses/list-expenses.component.html) as example.

Apply angular material in:

- [x] list-expense-items
- [x] list-categories
- [x] list-incomes
- [x] list-project
- [x] login (add hide and show password [how to](https://fireflysemantics.medium.com/angular-material-password-field-with-visibilitytoggle-d5342f97afbe))
- [x] register (add hide and show password [how to](https://fireflysemantics.medium.com/angular-material-password-field-with-visibilitytoggle-d5342f97afbe))

During this process we need to ensure that the layout will be good for edit on computers and mobiles.
And change the errors to be like we are using today in add forms for example this name field in `add-expense`:
``` html
@if (name?.invalid && name?.touched){
    <mat-error *ngFor="let error of getFormFieldErrors('name')">{{ error }}</mat-error>
}
```

**Comment by FelipePSoares** [comment]
Hi @AmirAbdollahi,

If you want to get some item, this would be a good one, because is easy and has some examples.
The another issue about the amount value I think that I will finish today at night.

**Comment by AmirAbdollahi** [comment]
> Hi @AmirAbdollahi,
> 
> If you want to get some item, this would be a good one, because is easy and has some examples.
> The another issue about the amount value I think that I will finish today at night.

Hi. Sure. Thanks a lot.

**Comment by AmirAbdollahi** [comment]
Hi @FelipePSoares.
The `list-expense-items` is complete. If there are any issues, I’d be happy to hear about them. Thank you!

![image](https://github.com/user-attachments/assets/f5868b43-b898-4da1-8b89-e0e003a4bb05)

![image](https://github.com/user-attachments/assets/7a6f243f-2454-457a-b9c8-b31d146a803a)

**Comment by FelipePSoares** [comment]
Hi @AmirAbdollahi ,

Looks perfect to me. Good job. Thanks

**Comment by AmirAbdollahi** [comment]
- [ ] ist-categories

## Before Changes

![image](https://github.com/user-attachments/assets/12b21f37-5285-4963-820e-1f481f94ebf9)

![image](https://github.com/user-attachments/assets/d009bfa0-3637-41a2-97c2-f6e8aecd5fde)


## After Changes

![image](https://github.com/user-attachments/assets/9bfa7c84-0022-4bd6-b492-1538701c8a1b)

![image](https://github.com/user-attachments/assets/292d7734-00f7-4303-8fe0-7d3a65bc1dcc)

**Comment by AmirAbdollahi** [comment]
- [ ]  list-incomes

## Before Changes

![image](https://github.com/user-attachments/assets/eaf59584-0177-4991-9ed1-e858ffd02ec1)

![image](https://github.com/user-attachments/assets/10f5a537-8b88-45ba-b475-5a4d89385592)


## After Changes

![image](https://github.com/user-attachments/assets/cf0b3a48-2813-4216-9308-fdb4ab9b005b)

![image](https://github.com/user-attachments/assets/60f09ad1-89b0-4361-81f6-9b338e409617)

**Comment by AmirAbdollahi** [comment]
- [ ]  list-project

## Before Changes

![image](https://github.com/user-attachments/assets/a982dcc0-c793-4d5b-a9ee-94a91edafdd1)

![image](https://github.com/user-attachments/assets/54b7b759-75fc-437a-94db-3da9c2455810)

## After Changes

* Project type field is `readonly`

![image](https://github.com/user-attachments/assets/762c7bcf-c831-45b0-9809-dd531a4dc18e)

![image](https://github.com/user-attachments/assets/47b31c4f-5bd7-437a-9fb8-13d5443c367d)

**Comment by AmirAbdollahi** [comment]
- [ ] login

## Before Changes

![image](https://github.com/user-attachments/assets/f58b49cc-d538-441c-af7b-7a6aeb3257ca)

## After Changes

![image](https://github.com/user-attachments/assets/4eb88428-07cf-4944-8fa1-492743742efe)

![image](https://github.com/user-attachments/assets/8cdf0543-cfa3-42fe-9d38-9616aa7cdf9e)

**Comment by AmirAbdollahi** [comment]
- [ ] register

## Before Changes

![image](https://github.com/user-attachments/assets/23094fba-b391-4f35-8862-13379de984af)

## After Changes

![image](https://github.com/user-attachments/assets/70727328-c635-4fe7-82f1-6f88b593edde)
