### ISSUE TITLE
[Frontend] Create Currency Formatting Pipe

### ISSUE THREAD

**Issue by FelipePSoares** [FelipePSoares/EconoFlow#243]
Develop a custom Angular pipe to format currency based on the user’s `PreferredCurrency` and use the system’s format for that currency.

- [ ] Implement a `CurrencyFormatPipe` that retrieves the user’s `PreferredCurrency` and formats amounts using Angular’s `CurrencyPipe` with the system’s default settings for that currency.
- [ ] Test to confirm it works with various currencies.

**Comment by ahmedhalac** [comment]
So, is this task just to create and test this pipe, but not to apply it across the codebase?

**Comment by FelipePSoares** [comment]
Exactly, I split it in various issues to be easier to develop and test it. If you look for issues on the project board, could be better because it's ordered there.

https://github.com/users/FelipePSoares/projects/1

**Comment by ahmedhalac** [comment]
> Exactly, I split it in various issues to be easier to develop and test it. If you look for issues on the project board, could be better because it's ordered there.
> 
> https://github.com/users/FelipePSoares/projects/1

Okay, Iwill handle this one.
