### ISSUE TITLE
[Frontend] Increase spacing between text elements on the login page

### ISSUE THREAD

**Issue by ahmedhalac** [FelipePSoares/EconoFlow#257]
Hi @FelipePSoares. Do you think we should add more space on the top of these two text elements?

<img width="389" alt="Screenshot 2024-11-18 at 10 21 55 PM" src="https://github.com/user-attachments/assets/395f4d14-149a-4618-a827-e83bf2cbb871">

It looks better for me:

<img width="390" alt="Screenshot 2024-11-18 at 10 22 37 PM" src="https://github.com/user-attachments/assets/45d76117-1433-41ba-b4c0-59594d523ea5">

**Comment by FelipePSoares** [comment]
Yeah prefect thank you. Maybe we can take the advantage and change this form to use angular material as well.

**Comment by ahmedhalac** [comment]
@FelipePSoares do u have any idea why I am getting this error while running the app?

<img width="1074" alt="Screenshot 2024-11-18 at 11 15 15 PM" src="https://github.com/user-attachments/assets/90ed4936-b964-47e6-9642-88f61653f40e">

**Comment by FelipePSoares** [comment]
Yes,

This happen because when you start the application in debug mode I create some data to help the tests. But it's based on UTC and because your fuse this error could appears. But we can solve this easily.

Let me send to you some modification to add on program.cs

**Comment by FelipePSoares** [comment]
Please change this part of the code on program.cs

I just change the DateTime.Now for DateTime.Now.AddDays(-1). 

```
    var expense = new Expense("Rent", DateTime.Now.AddDays(-1), 700, user, budget: 700);
    unitOfWork.ExpenseRepository.InsertOrUpdate(expense);

    var expense2 = new Expense("Groceries", DateTime.Now.AddDays(-1), 0, user, budget: 450);
    var expenseItem = new ExpenseItem("Pingo Doce", DateTime.Now.AddDays(-1), 100, user);
    expenseItem.SetId(new Guid("16ddf6c1-6b33-4563-dac4-08dcf73a4157"));
    var expenseItem2 = new ExpenseItem("Continente", DateTime.Now.AddDays(-1), 150, user);
```

If after that you continue receiving this error please let me know.

**Comment by ahmedhalac** [comment]
@FelipePSoares what do you think? Do I need to change anything additionaly?

<img width="393" alt="Screenshot 2024-11-18 at 11 49 14 PM" src="https://github.com/user-attachments/assets/753fa2d1-4572-49a0-9933-ffc1ba2e529e">

**Comment by FelipePSoares** [comment]
@ahmedhalac, for me is perfect, if you want you can check the register page also, that need to change to angular material and maybe we have the same problem with space.
