### ISSUE TITLE
[Frontend] Fix register page layout

### ISSUE THREAD

**Issue by FelipePSoares** [FelipePSoares/EconoFlow#265]
Our register page has some layout errors.

First of all the "sign up" button, is on left and small and should be like the "sign in" button on login page.
![IMG_20241124_200824.jpg](https://github.com/user-attachments/assets/a8dffb52-887c-4c70-a927-0ca2e82871de)

Than when you have some error message, this message stays behind the other field. We need to fix in a way to show the error message like in the user page.
![IMG_20241124_201150.jpg](https://github.com/user-attachments/assets/daa04881-7b8a-4b1d-92e9-d0b790b3630b)

**Comment by AmirAbdollahi** [comment]
- [ ] fix Sign up button size and position

![image](https://github.com/user-attachments/assets/fd19091e-4640-483c-89ef-c3008d8ade7a)

**Comment by AmirAbdollahi** [comment]
- [ ] fix error messages:

![image](https://github.com/user-attachments/assets/7f5cfd89-24e6-44ed-b2f8-f48d1f98613f)
