### ISSUE TITLE
[Backend] User Account Deletion

### ISSUE THREAD

**Issue by FelipePSoares** [FelipePSoares/EconoFlow#266]
[Backend]
Create an endpoint to allow users to delete their own accounts. The following conditions must be handled:

1. Data Handling:
   - If the user is linked as the creator of any expenses, expense items, or incomes, update those records:
      - Set the Creator reference to null.
      - Add a new column CreatorName (if not already existing) and populate it with the user's current name to preserve historical context.

2. Project Association:
   - If the user is the sole administrator of any project:
      - The project should be deleted, along with all related data.
   - If the project has additional administrators:
      - Remove the user from the project while ensuring the project and its data remain intact.

3. Final Cleanup:
   - After handling all associations and dependencies:
      - Delete the user account.
      - Delete any projects solely linked to the user.

**Comment by Bugbuster2004** [comment]
hey @FelipePSoares  i would like to work on this issue as it seems interesting

**Comment by FelipePSoares** [comment]
Hi @Bugbuster2004 ,

I'm sorry but I'm already working on it.

But if you want to contribute you are welcome you can choose any issue that is not assigned to anyone.

**Comment by Bugbuster2004** [comment]
okay no worries thank you very much
