### ISSUE TITLE
[Frontend] User Account Deletion

### ISSUE THREAD

**Issue by FelipePSoares** [FelipePSoares/EconoFlow#267]
1. Danger Zone for Account Deletion:
   - On the User Settings page, add a danger zone styled in red to clearly differentiate it from other settings.
   - Position the danger zone below all existing configuration sections.

2. Delete Account Button:
   - Include a Delete Account button inside the danger zone.
   - Clicking the button triggers a modal dialog.

3. Confirmation Modal:
   - Display the following elements in the modal:
      - Warning Message: “This action is permanent and cannot be undone. Are you sure you want to delete your account?”
      - Administrator Warning (if applicable):
         - If the user is an administrator for any project, show:
            - "You are associated as an administrator with one or more projects. Please transfer the administration to another user before deleting your account. Otherwise, the project(s) will be deleted."

      - Confirmation Buttons:
         - A "Cancel" button to close the modal.
         - A "Confirm Deletion" button to call the backend endpoint.

4. Error Handling and Feedback:
   - If the backend returns an error (e.g., unable to delete due to untransferred admin roles), display an appropriate message to the user.

**Comment by saksham-malhotra-27** [comment]
Hey @FelipePSoares is this issue still open? I find it interesting and would love to contribute !

**Comment by saksham-malhotra-27** [comment]
Sure! I'd be happy to contribute. I'll start with #220, and then move on to this one, or feel free to let me know if you'd prefer a specific order!

**Comment by FelipePSoares** [comment]
Perfect, I agree with that, I need to finish the backend for this one also.

**Comment by FelipePSoares** [comment]
Hey @saksham-malhotra-27!

I created the backend for this issue, now you are free to start it when you want.

https://github.com/FelipePSoares/EconoFlow/pull/276

**Comment by saksham-malhotra-27** [comment]
Hey @FelipePSoares ! 
I’ve implemented the following:

1. Danger Zone for Account Deletion
2. Delete Account Button
3. Confirmation Modal

I have a couple of questions:
Does the backend delete query return any errors if the user is an admin of a project? I’m concerned that it might delete everything related to the user right away.

Here’s an image for reference:
![image](https://github.com/user-attachments/assets/a4bcfa87-f5b5-415f-a4db-f91d85468ba1)

**Comment by FelipePSoares** [comment]
Hey @saksham-malhotra-27, 

No, the backend will just delete or remove link for the project. I'll create today an endpoint for you call and check if the user is admin of any project inside projectservice.

Do you have any other question?

**Comment by saksham-malhotra-27** [comment]
Hey @FelipePSoares ! 

It would be great if there was an endpoint for the frontend to check if the user is an admin of any project within the project service. However, wouldn't it be even better if this check was also incorporated into the delete service? Because if I rely solely on the frontend checker API to disable deletion, someone could still directly call the backend deletion API with credentials, which would bypass the check and allow deletion.

Let me know once you've implemented whatever you think works best!

**Comment by FelipePSoares** [comment]
Ja good one, but how do you think that could I do that? A property on back end `confirmDelete` when is false I'll check if the user is admin of any project and return error and if its true I'll proceed with the deletion?

**Comment by saksham-malhotra-27** [comment]
Hey @FelipePSoares!

Yes, that’s a good approach! You can add a _confirmDelete_ property to the backend API. However, managing the _boolean_ could become tricky, as you'd need to modify it in multiple places. 

So, If you’ve initialized a _boolean_ for each user (defaulting to false), the admin checker can make it to true if the user is **not an admin**. This would solve the issue. If the user is an admin to any of the projects, the warning may appear on the frontend. Even if the user tries a **_DELETE_** query, the _boolean_ would remain false, preventing deletion.

**Comment by FelipePSoares** [comment]
Hey @saksham-malhotra-27!

I looked a little bit in the internet and decided for a `Token-Based Confirmation` I created a [issue](https://github.com/FelipePSoares/EconoFlow/issues/277) to handle it, you can see it in the issue and prepare the front end for that, what do you think about this approach?

**Comment by FelipePSoares** [comment]
Hey @saksham-malhotra-27!

I think that now you have everything that you need to complete this issue, but let me know if you have any problem or need anything.

**Comment by saksham-malhotra-27** [comment]
@FelipePSoares Yep, gathered everything for this issue. I'll start working on it now.

**Comment by saksham-malhotra-27** [comment]
@FelipePSoares  Hey! I implemented the functionality shown here:

https://github.com/user-attachments/assets/901d1f25-717a-4ac5-a05c-6cab1719a8dc

Quick question—I'm currently using a browser alert, as you can see in the video. Do you think I should replace it with a custom modal alert instead?

**Comment by FelipePSoares** [comment]
Hey @saksham-malhotra-27,

Yes, the objective was you show the message inside that modal that you show in the beginning.

And then after confirm, don't need to show any message, just logout directly.

But it's a nice job.

**Comment by FelipePSoares** [comment]
The flow is the user click in the button. You call the backend get te confirmation message and show the modal with this message than the user click in cancel or confirm inside modal, if confirm you call the backend with the confirm token and delete the account.

**Comment by saksham-malhotra-27** [comment]
Hey @FelipePSoares , 

Got it! I’ve made the required changes:
https://github.com/user-attachments/assets/aaeb91ca-1eb1-41ef-9a0a-19b2c4fb55cf

Current Implementation works in this way:  
![image](https://github.com/user-attachments/assets/faed92fd-2447-44ae-a189-26702e59049a)

**Comment by saksham-malhotra-27** [comment]
Hey @FelipePSoares!
Thanks for your feedback!
Since we need a centralized approach to handle the token, I created this _tokenService_, which is simply a collection of straightforward methods:
![image](https://github.com/user-attachments/assets/70c481e3-1cca-4882-9f0e-ed08b3130f42)

Here's the current implementation:
https://github.com/user-attachments/assets/d5461f28-d6d5-41d3-b880-8f512e28c8e8

Let me know your thoughts!

**Comment by FelipePSoares** [comment]
Good, this is the expected behavior. Nice job.

Thanks

**Comment by saksham-malhotra-27** [comment]
Alright so, let me test it out and then I'll make the PR

**Comment by FelipePSoares** [comment]
Good, let me know if you need something.

**Comment by FelipePSoares** [comment]
Hey @saksham-malhotra-27 !

I "stole" this idea of danger zone from github. kkkk
I was configuring the repository and saw that and liked. kkk Thank you to help me to accomplish it.

![image](https://github.com/user-attachments/assets/a463a599-1f3a-48c4-a8a0-fc24cc76640b)

**Comment by saksham-malhotra-27** [comment]
@FelipePSoares No problem, the idea is actually great! I have one more question though — does the token expire after 5 minutes? I’m able to delete my account even after 10 minutes with the same token, which seems to be older than that.

**Comment by FelipePSoares** [comment]
@saksham-malhotra-27 maybe I made something wrong in the backend but don't worry I can test it later and fix it.

Thank you.
