### ISSUE TITLE
[Backend] Modify UserProject model

### ISSUE THREAD

**Issue by FelipePSoares** [FelipePSoares/EconoFlow#272]
We need to add some properties to UserProject Model to be possible work with invitation in the projects.

``` C#
    public User User { get; private set; } = new User(); // Already exists, change to optional
    public string Email { get; set; } // when user not exists
    public Project Project { get; private set; } = new Project();  // Already exists
    public Role Role { get; private set; }  // Already exists
    public Guid Token { get; set; }
    public bool Accepted { get; set; }
    public DateTime SentAt { get; set; }
    public DateTime? AcceptedAt { get; set; }
    public bool Expired { get; set; }
    public DateTime ExpiryDate { get; set; }
```
- [ ] create a index on token property

**Comment by FelipePSoares** [comment]
Hey @AmirAbdollahi ,

Are you still working on it?

I'm just asking because if you are not I'll release it to another one.

Thank you in advance.

**Comment by AmirAbdollahi** [comment]
Hi @FelipePSoares .
No I'm not. You can release it. 
Thank your very much.

**Comment by FelipePSoares** [comment]
Hi @AmirAbdollahi ,

No problem, Thank you very much for everything.

**Comment by FelipePSoares** [comment]
Hey @saksham-malhotra-27!

This one is a "simple" backend task if you want. You will need generate a migration after change the domain, you can find the instructions for that in contribution.md file.

If you accept the challenge, let me know any doubt that you could have.

**Comment by saksham-malhotra-27** [comment]
Yup @FelipePSoares ! alright I'll try

**Comment by saksham-malhotra-27** [comment]
or have you already completed the task ?

**Comment by FelipePSoares** [comment]
@saksham-malhotra-27 I know that you can handle with it. Let me know anything that you need.
